# -*- coding: utf-8 -*-
"""Week2_Assignment_Intellicore.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rT0RyNbBEWrfaVN5fVmctCTfGo-_QUDY
"""

